### ISSUE TITLE
ImportError: cannot import name 'json' from 'engineio'

### ISSUE THREAD

**Issue by chanduthedev** [RasaHQ/financial-demo#119]
I got the below error.

```

Traceback (most recent call last):
  File "/Users/cpasumarthi/codeBase/chatbot/venv/bin/rasa", line 6, in <module>
    from rasa.__main__ import main
  File "/Users/cpasumarthi/codeBase/chatbot/venv/lib/python3.7/site-packages/rasa/__init__.py", line 9, in <module>
    from rasa.train import train
  File "/Users/cpasumarthi/codeBase/chatbot/venv/lib/python3.7/site-packages/rasa/train.py", line 39, in <module>
    from rasa.core.agent import Agent
  File "/Users/cpasumarthi/codeBase/chatbot/venv/lib/python3.7/site-packages/rasa/core/agent.py", line 15, in <module>
    from rasa.core.channels.channel import OutputChannel, UserMessage
  File "/Users/cpasumarthi/codeBase/chatbot/venv/lib/python3.7/site-packages/rasa/core/channels/__init__.py", line 12, in <module>
    from rasa.core.channels.socketio import SocketIOInput
  File "/Users/cpasumarthi/codeBase/chatbot/venv/lib/python3.7/site-packages/rasa/core/channels/socketio.py", line 10, in <module>
    from socketio import AsyncServer
  File "/Users/cpasumarthi/codeBase/chatbot/venv/lib/python3.7/site-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/Users/cpasumarthi/codeBase/chatbot/venv/lib/python3.7/site-packages/socketio/client.py", line 11, in <module>
    from . import packet
  File "/Users/cpasumarthi/codeBase/chatbot/venv/lib/python3.7/site-packages/socketio/packet.py", line 2, in <module>
    from engineio import json as _json
ImportError: cannot import name 'json' from 'engineio' 

```

#### This error is due to an incompatible version of  python-engineio library as shown below. It worked fine after upgrading the version

```
ERROR: rasa 2.4.0 has requirement python-engineio<3.14,>=3.11, but you'll have python-engineio 4.2.0 which is incompatible.
```

### Environment:
**OS:** Big Sur 11.4
**Python:** 3.7.7

**Comment by sara-tagger** [comment]
Thanks for the issue, @koernerfelicia will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koernerfelicia** [comment]
Thank you for letting us know. Closing the issue as it seems to have been fixed with the correct version of engineio.
