### ISSUE TITLE
RuntimeError: This event loop is already running

### ISSUE THREAD

**Issue by swayson** [RasaHQ/financial-demo#36]
When I try and test the bot with `rasa shell --debug` I get a runtime error and it seems the process gets blocked as there is no response from the bot if I try and interact.

```
rasa shell --debug
2020-06-04 09:05:52 DEBUG    rasa.model  - Extracted model to 'C:\Users\USERNAME\AppData\Local\Temp\1\tmpjzm3he9j'.
2020-06-04 09:05:52 DEBUG    rasa.cli.utils  - Parameter 'endpoints' not set. Using default location 'endpoints.yml' instead.
2020-06-04 09:05:52 DEBUG    rasa.cli.utils  - Parameter 'credentials' not set. Using default location 'credentials.yml' instead.
2020-06-04 09:05:52 DEBUG    rasa.model  - Extracted model to 'C:\Users\USERNAME\AppData\Local\Temp\1\tmpklfl9j12'.
2020-06-04 09:05:55 INFO     root  - Connecting to channel 'cmdline' which was specified by the '--connector' argument. Any other channels will be ignored. To connect to all given channels, omit the '--connector' argument.
2020-06-04 09:05:55 DEBUG    sanic.root  - CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': None, 'supports_credentials': True, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2020-06-04 09:05:55 DEBUG    rasa.core.utils  - Available web server routes:
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
/                                                  GET                            hello
2020-06-04 09:05:55 INFO     root  - Starting Rasa server on http://localhost:5005
2020-06-04 09:05:55 DEBUG    rasa.core.utils  - Using the default number of Sanic workers (1).
2020-06-04 09:05:55 INFO     root  - Enabling coroutine debugging. Loop id 2401635131176.
2020-06-04 09:05:55 DEBUG    rasa.model  - Extracted model to 'C:\Users\USERNAME\AppData\Local\Temp\1\tmpa4tr7si9'.
c:\users\USERNAME\appdata\local\continuum\miniconda3\envs\findemo\lib\site-packages\thinc\neural\_custom_kernels.py:36: ResourceWarning: unclosed file <_io.TextIOWrapper name='c:\\users\\USERNAME\\appdata\\local\\continuum\\miniconda3\\envs\\findemo\\lib\\site-packages\\thinc\\neural\\_custom_kernels.cu' mode='r' encoding='utf8'>
  SRC = (PWD / "_custom_kernels.cu").open("r", encoding="utf8").read()
c:\users\USERNAME\appdata\local\continuum\miniconda3\envs\findemo\lib\site-packages\thinc\neural\_custom_kernels.py:39: ResourceWarning: unclosed file <_io.TextIOWrapper name='c:\\users\\USERNAME\\appdata\\local\\continuum\\miniconda3\\envs\\findemo\\lib\\site-packages\\thinc\\neural\\_murmur3.cu' mode='r' encoding='utf8'>
  MMH_SRC = (PWD / "_murmur3.cu").open("r", encoding="utf8").read()
2020-06-04 09:05:57 DEBUG    rasa.utils.tensorflow.models  - Loading the model ...
2020-06-04 09:05:58 DEBUG    rasa.utils.tensorflow.models  - Finished loading the model.
2020-06-04 09:05:58 DEBUG    rasa.utils.tensorflow.models  - Building tensorflow prediction graph...
2020-06-04 09:06:04 DEBUG    rasa.utils.tensorflow.models  - Finished building tensorflow prediction graph.
2020-06-04 09:06:24 INFO     rasa.nlu.components  - Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en_core_web_md'.
2020-06-04 09:06:24 DEBUG    rasa.core.tracker_store  - Connected to InMemoryTrackerStore.
2020-06-04 09:06:24 DEBUG    rasa.core.lock_store  - Connected to lock store 'InMemoryLockStore'.
2020-06-04 09:06:24 DEBUG    rasa.model  - Extracted model to 'C:\Users\USERNAME\AppData\Local\Temp\1\tmprkmgvsrh'.
2020-06-04 09:06:24 DEBUG    pykwalify.compat  - Using yaml library: c:\users\USERNAME\appdata\local\continuum\miniconda3\envs\findemo\lib\site-packages\ruamel\yaml\__init__.py
2020-06-04 09:06:25 DEBUG    rasa.utils.tensorflow.models  - Loading the model ...
2020-06-04 09:06:25 DEBUG    rasa.utils.tensorflow.models  - Finished loading the model.
2020-06-04 09:06:25 DEBUG    rasa.utils.tensorflow.models  - Building tensorflow prediction graph...
2020-06-04 09:06:26 DEBUG    rasa.utils.tensorflow.models  - Finished building tensorflow prediction graph.
2020-06-04 09:06:26 DEBUG    rasa.core.nlg.generator  - Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2020-06-04 09:06:26 INFO     root  - Rasa server is up and running.
Bot loaded. Type a message and press enter (use '/stop' to exit): 
2020-06-04 09:06:27 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done, defined at c:\users\USERNAME\appdata\local\continuum\miniconda3\envs\findemo\lib\site-packages\rasa\core\run.py:128> exception=RuntimeError('This event loop is already running',)>
Traceback (most recent call last):
  File "c:\users\USERNAME\appdata\local\continuum\miniconda3\envs\findemo\lib\site-packages\rasa\core\run.py", line 134, in run_cmdline_io
    sender_id=conversation_id,
  File "c:\users\USERNAME\appdata\local\continuum\miniconda3\envs\findemo\lib\asyncio\coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "c:\users\USERNAME\appdata\local\continuum\miniconda3\envs\findemo\lib\site-packages\rasa\core\channels\console.py", line 142, in record_messages
    text = get_user_input(button_question)
  File "c:\users\USERNAME\appdata\local\continuum\miniconda3\envs\findemo\lib\site-packages\rasa\core\channels\console.py", line 78, in get_user_input
    style=Style([("qmark", "#b373d6"), ("", "#b373d6")]),
  File "c:\users\USERNAME\appdata\local\continuum\miniconda3\envs\findemo\lib\site-packages\questionary\question.py", line 45, in ask
    return self.unsafe_ask(patch_stdout)
  File "c:\users\USERNAME\appdata\local\continuum\miniconda3\envs\findemo\lib\site-packages\questionary\question.py", line 59, in unsafe_ask
    return self.application.run()
  File "c:\users\USERNAME\appdata\local\continuum\miniconda3\envs\findemo\lib\site-packages\prompt_toolkit\application\application.py", line 812, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "c:\users\USERNAME\appdata\local\continuum\miniconda3\envs\findemo\lib\asyncio\base_events.py", line 475, in run_until_complete
    self.run_forever()
  File "c:\users\USERNAME\appdata\local\continuum\miniconda3\envs\findemo\lib\asyncio\base_events.py", line 429, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by swayson** [comment]
Realised now I experience this same problem with any rasa bot at the moment. Even the hello world `rasa init` version.

**Comment by TyDunn** [comment]
@swayson Does [this](https://forum.rasa.com/t/error-this-event-loop-is-already-running/24017) help?
