### ISSUE TITLE
time parsing for transaction search not working

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/financial-demo#40]
Asking "How much did I spend at Starbucks in the last two months?" results in 
```
app_1              | 2020-06-16 18:48:00 DEBUG    rasa_sdk.forms  - Submitting the form 'transact_search_form'
app_1              | Exception occurred while handling uri: 'http://app:5055/webhook'
app_1              | Traceback (most recent call last):
app_1              |   File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 976, in handle_request
app_1              |     response = await response
app_1              |   File "/app/rasa_sdk/endpoint.py", line 102, in webhook
app_1              |     result = await executor.run(action_call)
app_1              |   File "/app/rasa_sdk/executor.py", line 387, in run
app_1              |     events = await action(dispatcher, tracker, domain)
app_1              |   File "/app/rasa_sdk/forms.py", line 606, in run
app_1              |     events.extend(self.submit(dispatcher, temp_tracker, domain))
app_1              |   File "/app/actions/actions.py", line 314, in submit
app_1              |     from_date = date.fromisoformat(time_range.split("T")[0])
app_1              | ValueError: Invalid isoformat string: 'last two months'
```

**Comment by b-quachtran** [comment]
Is duckling running on this instance?

**Comment by melindaloubser1** [comment]
Yes, I found the issue - in the parsing file, it had from and too switched around. Also, the transaction dates were naive (not localized) while the extracted dates were, so they couldn't be compared. 
Fix incoming =)
