### ISSUE TITLE
Please improve readme instructions

### ISSUE THREAD

**Issue by samboustani** [RasaHQ/financial-demo#5]
- Are the commands shown in the readme executed in the virtual environment?

- Docker does not exist in the virtual environment after following the installation instructions on rasa.com.  There is a command in the readme that uses Docker.  Should we install Docker in the virtual environment?

- After installing Docker and running rasa/duckling, it says to do "rasa shell --debug" but where?  Do it in a third window?  If I do that it just says "the path 'models' does not exist". I already ran "rasa train".

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by xnuinside** [comment]
@sara-tagger, hi Sara! Can you also add in README.md information about steps with installation of spaCy models, e.g. by running:
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en

They are needed for ```rasa train``` command. Without them user will have an error as on screenshot. If you want I can open PR with README.md improvements. 
<img width="1054" alt="Screen Shot 2020-04-06 at 1 31 55 PM" src="https://user-images.githubusercontent.com/15959809/78549410-03167c00-780b-11ea-8194-98eaef345951.png">

**Comment by melindaloubser1** [comment]
@xnuinside To your question about where to run `rasa shell` - this should be run in another terminal, in the same virtual environment, in the head of the repo. 

If you'd like to open a PR with what you think would make the readme clearer, that would be great. Keep in mind, users on different OS's will have different setups e.g. docker is already installed in Ubuntu. Also, Docker is not installed in python, but on the system, so virtual environments don't come into play. Did you manage to get the bot running in the end?

**Comment by xnuinside** [comment]
@melindaloubser1, yes all works well, thank you. I just mentioned, that if you never use spacy - required to install SpaCy models :) no problems with up&run, sorry for long response

**Comment by swayson** [comment]
> Can anyone also add in README.md information about steps with installation of spaCy models, e.g. by running:
> python -m spacy download en_core_web_md
> python -m spacy link en_core_web_md en
> 
> They are needed for `rasa train` command. Without them user will have an error as on screenshot.
> 
> If needed help - I can open PR with README.md improvements.
> <img alt="Screen Shot 2020-04-06 at 1 31 55 PM" width="1054" src="https://user-images.githubusercontent.com/15959809/78549410-03167c00-780b-11ea-8194-98eaef345951.png">

For what it is worth, those behind a firewall may have issues downloading spacy artifacts that way. Alternative, is to download it manually from github releases and then do a pip install.

https://github.com/explosion/spaCy/issues/4297

**Comment by carlhung** [comment]
i run `rasa train` command. but i got the following error:
Traceback (most recent call last):
  File "/Users/carlhung/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/Users/carlhung/venv/lib/python3.7/site-packages/rasa/__main__.py", line 82, in main
    set_log_level(log_level)
  File "/Users/carlhung/venv/lib/python3.7/site-packages/rasa/utils/common.py", line 71, in set_log_level
    update_tensorflow_log_level()
  File "/Users/carlhung/venv/lib/python3.7/site-packages/rasa/utils/common.py", line 112, in update_tensorflow_log_level
    import tensorflow as tf
  File "/Users/carlhung/venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/Users/carlhung/venv/lib/python3.7/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 959, in _find_and_load_unlocked
  File "/Users/carlhung/venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/Users/carlhung/venv/lib/python3.7/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/carlhung/venv/lib/python3.7/site-packages/tensorflow_core/python/__init__.py", line 64, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/carlhung/venv/lib/python3.7/site-packages/tensorflow_core/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Users/carlhung/venv/lib/python3.7/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Users/carlhung/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 83, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/Users/carlhung/venv/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/carlhung/venv/lib/python3.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/Users/carlhung/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 4756, in <module>
    _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])
  File "/Users/carlhung/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1284, in setParseAction
    self.parseAction = list(map(_trim_arity, list(fns)))
  File "/Users/carlhung/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1066, in _trim_arity
    this_line = extract_stack(limit=2)[-1]
  File "/Users/carlhung/venv/lib/python3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1050, in extract_stack
    frame_summary = traceback.extract_stack(limit=-offset+limit-1)[offset]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 363, in extract
    f.line
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 48, in getlines
    for mod in sys.modules.values():
RuntimeError: dictionary changed size during iteration

**Comment by melindaloubser1** [comment]
@carlhung The [Rasa Forum](https://forum.rasa.com/) would be the right place for questions like that, because it isn't specific to this project. In this case similar questions have been asked e.g. https://forum.rasa.com/t/rasa-init-runtimeerror-dictionary-changed-size-during-iteration/25370 or you can ask your own question if you can't an answer that works for you.
