### ISSUE TITLE
domain error when training

### ISSUE THREAD

**Issue by henry-hz** [RasaHQ/financial-demo#59]
Thanks for working on this rasa example!

I am having this error after 'rasa train'.

>python 3.7.6
>rasa 1.10.9

```
❯ rasa train
Traceback (most recent call last):
  File "/home/henry/.venv/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/home/henry/.venv/lib/python3.7/site-packages/rasa/__main__.py", line 92, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/henry/.venv/lib/python3.7/site-packages/rasa/cli/train.py", line 76, in train
    additional_arguments=extract_additional_arguments(args),
  File "/home/henry/.venv/lib/python3.7/site-packages/rasa/train.py", line 50, in train
    additional_arguments=additional_arguments,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/henry/.venv/lib/python3.7/site-packages/rasa/train.py", line 101, in train_async
    additional_arguments,
  File "/home/henry/.venv/lib/python3.7/site-packages/rasa/train.py", line 172, in _train_async_internal
    new_fingerprint = await model.model_fingerprint(file_importer)
  File "/home/henry/.venv/lib/python3.7/site-packages/rasa/model.py", line 290, in model_fingerprint
    domain_without_nlg = Domain.from_dict(domain_dict)
  File "/home/henry/.venv/lib/python3.7/site-packages/rasa/core/domain.py", line 162, in from_dict
    **additional_arguments,
  File "/home/henry/.venv/lib/python3.7/site-packages/rasa/core/domain.py", line 431, in __init__
    self._check_domain_sanity()
  File "/home/henry/.venv/lib/python3.7/site-packages/rasa/core/domain.py", line 1049, in _check_domain_sanity
    incorrect_mappings,
rasa.core.domain.InvalidDomain: Intent 'handoff' is set to trigger action 'utter_greet', which is not defined in the domain.
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
Did you edit the domain at all? `utter_greet` is defined here:
https://github.com/RasaHQ/financial-demo/blob/c552ea1a3bbe3a27c26f9f72e315d94ccb4efdb3/domain.yml#L190

**Comment by henry-hz** [comment]
@melindaloubser1  using the same domain file as it it's... seems that the 'intent' is looking for the utter_greet as an 'action'. I will get into the details, just noticed that downloading and running directly crashes as above
```
Intent 'handoff' is set to trigger action 'utter_greet'
```

**Comment by melindaloubser1** [comment]
I can't reproduce this. Could you try doing a clean clone of the repo, checking out master, and running it again?

**Comment by melindaloubser1** [comment]
This seems to be a bug in Rasa 1.10.9. Issue opened here https://github.com/RasaHQ/rasa/issues/6336
