### ISSUE TITLE
Custom action issue

### ISSUE THREAD

**Issue by Rajatkhatri7** [RasaHQ/financial-demo#94]
To get the list of vendors i defined the new action vendor  in action.py. But on putting the query after retraining the model its showing no registered actions for action_vendor.

* Error
`ERROR    rasa.core.processor  - Encountered an exception while running action 'action_vendor'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/home/kush/.local/lib/python3.8/site-packages/rasa/core/actions/action.py", line 670, in run
    response = await self.action_endpoint.request(
  File "/home/kush/.local/lib/python3.8/site-packages/rasa/utils/endpoints.py", line 154, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 404, Not Found, body='b'{"error":"No registered action found for name \'action_vendor\'.","action_name":"action_vendor"}''
`

* defined action
`
class ActionVendor(Action):

    def name(self):
        return "action_vendor"

    def run(self, dispatcher, tracker, domain):
        vendors = tracker.get_slot("vendor_list")
        formatted_vendors = "\n" + "\n".join(
            [f"- {vendor}" for vendor in vendors]
        ) 
        dispatcher.utter_message(
            template="utter_vendors",
            formatted_vendors=formatted_vendors,
        )
        return []`

**Comment by sara-tagger** [comment]
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
What do the logs of your action server show?
